[package]
name = "es-terminal"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
es-manifest={path="../es-manifest",version="0.0.1"}
libc = "0.2.138"