[package]
name = "es-engine"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
es-parser={path="../es-parser",version="0.0.1"}
sha-1 = "0.10.0"