[package]
name = "es-parser"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
es-type={path="../es-type",version="0.0.1"}
es-ast={path="../es-ast",version="0.0.1"}